#!/bin/sh
# Generated by dockerbundle 0.2.0. Do not edit; change docker-bundle.yml and regenerate.
#
# Healthy means every critical program is RUNNING and every readiness probe answers.
# Non-critical programs (queue workers, dev servers) are reported but never fail the
# check: a restarting worker is not a reason to take the whole bundle out of rotation.
set -u

SOCK=unix:///run/bundle/supervisor.sock
status=0

if ! supervisorctl -s "$SOCK" pid >/dev/null 2>&1; then
    echo "supervisord is not answering on $SOCK"
    exit 1
fi

check_program() {
    name=$1
    state=$(supervisorctl -s "$SOCK" status "$name" 2>/dev/null | awk '{print $2}')
    case "$state" in
        RUNNING) return 0 ;;
        "")      echo "$name: unknown to supervisord"; return 1 ;;
        *)       echo "$name: $state"; return 1 ;;
    esac
}
check_program mysql || status=1
check_program php-fpm || status=1
check_program vue_nginx_vite_vue || echo "vue_nginx_vite_vue: not running (non-critical)"
check_program queue-laravel_nginx_laravel || echo "queue-laravel_nginx_laravel: not running (non-critical)"
check_program nginx || status=1
nc -z 127.0.0.1 3306 2>/dev/null || { echo "mysql: port 3306 closed"; status=1; }
nc -z 127.0.0.1 9000 2>/dev/null || { echo "laravel_nginx_laravel: port 9000 closed"; status=1; }
nc -z 127.0.0.1 80 2>/dev/null || { echo "laravel_nginx_nginx: port 80 closed"; status=1; }
nc -z 127.0.0.1 20000 2>/dev/null || { echo "vue_nginx_vite_nginx: port 20000 closed"; status=1; }

exit "$status"
