"""Render a :class:`~core.model.BundlePlan` into a self-contained ``dist/``.

Everything a build needs is staged under ``dist/context/`` so that ``docker build dist/``
works from anywhere, and so that CI can set ``BUILD_CONTEXT=dist`` without dragging the
whole repository into the build context.

Output is deterministic: the same plan produces byte-identical files, which is what makes
the golden tests meaningful and keeps ``git diff`` on a regenerated ``dist/`` readable.
"""

from __future__ import annotations

import hashlib
import shutil
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from core.model import BundlePlan, EnvVar, PlannedService
from core.paths import resource_dir
from core.version import GENERATOR_VERSION, __version__
from plan.builder import INIT_BARRIER

HEADER = "# Generated by dockerbundle {version}. Do not edit; change bundle.yml and regenerate."
HEADER_PLAIN = "Generated by dockerbundle {version}. Do not edit; change bundle.yml and regenerate."

#: Docker's healthcheck start period. Long enough that a first start doing composer
#: install or a model download is not reported unhealthy while it works.
DEFAULT_START_PERIOD = 120


@dataclass
class Written:
    directory: Path
    files: list[Path] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def _environment() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(resource_dir("render/templates"))),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    return env


def _write(path: Path, text: str, written: Written, *, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Always LF: these files run inside Linux containers, and a CRLF shebang line makes
    # the kernel report "no such file or directory" in a way that is baffling to debug.
    path.write_text(text.replace("\r\n", "\n"), encoding="utf-8", newline="\n")
    if executable:
        path.chmod(0o755)
    written.files.append(path)


#: Keys the .env.example header writes itself. Emitting them again from the merged
#: catalogue would put the same name in the file twice.
HEADER_KEYS = frozenset({"BUNDLE_IMAGE", "INSTANCE", "GPU_COUNT"})


def _sections(entries: list[EnvVar]) -> dict[str, list[EnvVar]]:
    """Group merged env entries into readable sections, globals first."""
    order = ["global", "shared"]
    sections: dict[str, list[EnvVar]] = {}
    for entry in entries:
        if entry.key in HEADER_KEYS:
            continue
        sections.setdefault(entry.source or "other", []).append(entry)

    ordered: dict[str, list[EnvVar]] = {}
    for key in order:
        if key in sections:
            ordered[key] = sections.pop(key)
    for key in sorted(sections):
        ordered[key] = sections[key]
    return ordered


def _published(plan: BundlePlan) -> list[str]:
    """Host publish specs for the bundle container.

    A service that kept its original port keeps whatever compose published it on; a
    service that had to move is published on its new port so it stays reachable.
    """
    entries: list[str] = []
    seen: set[str] = set()
    for service in plan.baked:
        for port in service.ports:
            if port.remapped or not port.published:
                spec = f"127.0.0.1:{port.container}:{port.container}"
            else:
                spec = f"{port.published}:{port.container}"
            if spec not in seen:
                seen.add(spec)
                entries.append(spec)
    return entries


def _replica_vars(plan: BundlePlan) -> dict[str, int]:
    return {p.replicas_var: 1 for p in plan.programs if p.replicas_var}


def _readiness_before_init(plan: BundlePlan) -> list:
    """Probes worth waiting on before init scripts run.

    Only data services qualify: application processes have not been released yet, so
    waiting for them would simply burn the timeout.
    """
    data_services = {
        service.spec.slug
        for service in plan.baked
        for program in service.programs
        if program.priority < INIT_BARRIER
    }
    return [probe for probe in plan.readiness if probe.label in data_services]


def _recipe_reason(service: PlannedService) -> str:
    return "kept outside the image by its recipe"


def stage_context(plan: BundlePlan, context: Path, written: Written) -> None:
    """Copy everything the Dockerfile's COPY lines reference into ``context/``."""
    if context.exists():
        shutil.rmtree(context)
    context.mkdir(parents=True, exist_ok=True)

    for service in plan.baked:
        for copy in service.copies:
            destination = context / copy.context
            destination.parent.mkdir(parents=True, exist_ok=True)
            if copy.source.is_dir():
                shutil.copytree(copy.source, destination, dirs_exist_ok=True)
            else:
                shutil.copy2(copy.source, destination)

    bundle_dir = context / "_bundle"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    if plan.stages:
        merge = resource_dir("render/assets") / "merge-rootfs.sh"
        _write(bundle_dir / "merge-rootfs.sh", merge.read_text(encoding="utf-8"), written,
               executable=True)


def render(plan: BundlePlan, output: Path, *, variant: str = "cpu", image_ref: str = "") -> Written:
    """Write the whole ``dist/`` tree and return what was produced."""
    written = Written(directory=output, warnings=list(plan.warnings))
    env = _environment()
    output.mkdir(parents=True, exist_ok=True)

    context = output / "context"
    stage_context(plan, context, written)

    image_ref = image_ref or f"{plan.name}:latest"
    base_image = plan.base_images.get(variant, "debian:bookworm-slim")
    cuda = "cuda" in variant or "cuda" in base_image
    common = {
        "plan": plan,
        "header": HEADER.format(version=__version__),
        "header_plain": HEADER_PLAIN.format(version=__version__),
        "variant": variant,
        "base_image": base_image,
        "family": plan.family,
        "image_ref": image_ref,
        "cuda": cuda,
        "start_period": DEFAULT_START_PERIOD,
    }

    # Dockerfile
    _write(
        output / "Dockerfile",
        env.get_template("Dockerfile.j2").render(
            **common,
            install=plan.install.get(plan.family, []),
            run_steps=plan.run_steps.get(plan.family, []),
            exposed_ports=sorted({p.container for s in plan.baked for p in s.ports}),
        ),
        written,
    )

    # supervisord
    _write(output / "supervisord.conf",
           env.get_template("supervisord.conf.j2").render(**common), written)
    _write(context / "_bundle" / "supervisord.conf",
           (output / "supervisord.conf").read_text(encoding="utf-8"), written)

    # entrypoint
    entrypoint = env.get_template("entrypoint.sh.j2").render(
        **common,
        needs_init=plan.needs_init,
        readiness_before_init=_readiness_before_init(plan),
    )
    _write(output / "entrypoint.sh", entrypoint, written, executable=True)
    _write(context / "_bundle" / "entrypoint.sh", entrypoint, written, executable=True)

    # healthcheck
    healthcheck = env.get_template("healthcheck.sh.j2").render(**common)
    _write(output / "healthcheck.sh", healthcheck, written, executable=True)
    _write(context / "_bundle" / "healthcheck.sh", healthcheck, written, executable=True)

    # compose
    for service in plan.sidecars:
        service.recipe_reason = _recipe_reason(service)  # type: ignore[attr-defined]
    _write(
        output / "docker-compose.yml",
        env.get_template("docker-compose.yml.j2").render(
            **common,
            published_ports=_published(plan),
            labels=[],
        ),
        written,
    )

    # .env.example
    _write(
        output / ".env.example",
        env.get_template("env.example.j2").render(
            **common,
            sections=_sections(plan.env),
            replica_vars=_replica_vars(plan),
        ),
        written,
    )

    _write(output / ".dockerignore", "context/**/.git\n**/__pycache__\n**/node_modules\n", written)
    _write(output / "bundle.lock.yml", _lock(plan, variant, image_ref, context), written)

    return written


def _lock(plan: BundlePlan, variant: str, image_ref: str, context: Path) -> str:
    """A record of what was generated: port map, digests, versions.

    Makes a regenerated ``dist/`` diffable and gives operators the port map in one place
    without reading the Dockerfile.
    """
    payload = {
        "generator": {"version": __version__, "format": GENERATOR_VERSION},
        "bundle": {"name": plan.name, "variant": variant, "image": image_ref},
        "base_image": plan.base_images.get(variant, ""),
        "ports": {
            slug: [
                {"original": p.original, "assigned": p.container, "moved": p.remapped}
                for p in entries
            ]
            for slug, entries in sorted(plan.port_map.items())
            if entries
        },
        "programs": [
            {
                "name": p.name,
                "priority": p.priority,
                "autostart": p.autostart,
                "scalable": p.scalable,
                "critical": p.critical,
            }
            for p in plan.programs
        ],
        "baked": sorted(s.spec.slug for s in plan.baked),
        "sidecars": sorted(s.spec.slug for s in plan.sidecars),
        "volumes": dict(sorted(plan.named_volumes.items())),
        "env_renames": {k: dict(sorted(v.items())) for k, v in sorted(plan.env_renames.items())},
        "context_digest": _digest(context),
    }
    return yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, default_flow_style=False)


def _digest(context: Path) -> str:
    """A stable digest of the staged build context."""
    if not context.is_dir():
        return ""
    hasher = hashlib.sha256()
    for path in sorted(p for p in context.rglob("*") if p.is_file()):
        hasher.update(str(path.relative_to(context)).replace("\\", "/").encode())
        hasher.update(path.read_bytes())
    return f"sha256:{hasher.hexdigest()}"
