"""Render a :class:`~core.model.BundlePlan` into a self-contained ``dist/``.

Everything a build needs is staged under ``dist/context/`` so that ``docker build dist/``
works from anywhere, and so that CI can set ``BUILD_CONTEXT=dist`` without dragging the
whole repository into the build context.

Output is deterministic: the same plan produces byte-identical files, which is what makes
the golden tests meaningful and keeps ``git diff`` on a regenerated ``dist/`` readable.
"""

from __future__ import annotations

import hashlib
import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from core.model import BundlePlan, EnvVar, PlannedService
from core.paths import LOCK_NAME, resource_dir
from core.version import GENERATOR_VERSION, __version__
from discover.interpolate import (
    has_default,
    referenced_names,
    rename_variables,
    strip_defaults,
)
from plan.builder import INIT_BARRIER

_HEADER_TEXT = (
    "Generated by dockerbundle {version}. "
    "Do not edit; change docker-bundle.yml and regenerate."
)
HEADER = f"# {_HEADER_TEXT}"
HEADER_PLAIN = _HEADER_TEXT

#: Docker's healthcheck start period. Long enough that a first start doing composer
#: install or a model download is not reported unhealthy while it works.
DEFAULT_START_PERIOD = 120


@dataclass
class Written:
    directory: Path
    files: list[Path] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


def _environment() -> Environment:
    env = Environment(
        loader=FileSystemLoader(str(resource_dir("render/templates"))),
        undefined=StrictUndefined,
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )
    return env


def _write(path: Path, text: str, written: Written, *, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Always LF: these files run inside Linux containers, and a CRLF shebang line makes
    # the kernel report "no such file or directory" in a way that is baffling to debug.
    path.write_text(text.replace("\r\n", "\n"), encoding="utf-8", newline="\n")
    if executable:
        path.chmod(0o755)
    written.files.append(path)


#: Keys the .env.example header writes itself. Emitting them again from the merged
#: catalogue would put the same name in the file twice.
HEADER_KEYS = frozenset({"BUNDLE_IMAGE", "INSTANCE", "GPU_COUNT"})


def _sections(entries: list[EnvVar]) -> dict[str, list[EnvVar]]:
    """Group merged env entries into readable sections, globals first."""
    order = ["global", "shared"]
    sections: dict[str, list[EnvVar]] = {}
    for entry in entries:
        if entry.key in HEADER_KEYS:
            continue
        sections.setdefault(entry.source or "other", []).append(entry)

    ordered: dict[str, list[EnvVar]] = {}
    for key in order:
        if key in sections:
            ordered[key] = sections.pop(key)
    for key in sorted(sections):
        ordered[key] = sections[key]
    return ordered


def _published(plan: BundlePlan) -> list[str]:
    """Host publish specs for the bundle container.

    A service that kept its original port keeps whatever compose published it on; a
    service that had to move is published on its new port so it stays reachable.

    Where the package published through a variable — ``ports: ["${EXTERNAL_ACCESS}"]``,
    which is how every package in this style is written — the reference is passed through
    instead of its current value, so the deployment can still move the port from its
    ``.env``. That only holds while the container port is unchanged: once a collision has
    moved the service, the variable describes a mapping that no longer exists.
    """
    entries: list[str] = []
    seen: set[str] = set()
    for service in plan.baked:
        renames = plan.env_renames.get(service.spec.slug, {})
        # Only a one-to-one pairing is trustworthy: an entry whose variable was empty at
        # generation time parsed to nothing and left the two lists out of step.
        raw_ports = service.spec.raw_ports
        paired = raw_ports if len(raw_ports) == len(service.ports) else []

        for index, port in enumerate(service.ports):
            spec = ""
            if paired and not port.remapped and "$" in paired[index]:
                spec = rename_variables(paired[index], renames)
            elif port.remapped or not port.published:
                spec = f"127.0.0.1:{port.container}:{port.container}"
            else:
                spec = f"{port.published}:{port.container}"
            if spec not in seen:
                seen.add(spec)
                entries.append(spec)
    return entries


#: Traefik's way of naming the port a router's backend listens on. It is the one label
#: whose value the bundle cannot pass through untouched, because port remapping may have
#: moved the service off the port it asked for.
_LOADBALANCER_PORT = re.compile(r"^traefik\.http\.services\..+\.loadbalancer\.server\.port$")


def _labels(
    plan: BundlePlan, declared: dict[str, str] | None = None
) -> tuple[list[str], list[str]]:
    """Container labels for the bundle, gathered from the services it baked.

    Baking collapses several containers into one, and a router pointed at a container
    that no longer exists routes nowhere — so the labels have to move with the services.
    Three adjustments on the way:

    * ``loadbalancer.server.port`` is retargeted when the service was moved off its
      original port by a collision;
    * keys are emitted once. A label describes the *container*, so where two services
      genuinely disagree there is no value that satisfies both. Comparison ignores how a
      reference was typed: ``${X}`` and ``${X:-true}`` resolve alike whenever ``X`` is
      set, and the spelling with a fallback is kept because it also survives when it is
      not. Only a real divergence — a different variable, a different literal — is
      reported, and the first value stands;
    * ``labels`` in ``docker-bundle.yml`` wins over everything, which is the only way to settle
      a real divergence rather than live with whichever service came first.

    Returns the label list and any warnings raised while merging.
    """
    entries: dict[str, str] = {}
    owner: dict[str, str] = {}
    warnings: list[str] = []

    for service in plan.baked:
        renames = plan.env_renames.get(service.spec.slug, {})
        moved = {port.original: port.container for port in service.ports}

        for key, raw_value in service.spec.declared_labels.items():
            value = rename_variables(str(raw_value), renames)
            if _LOADBALANCER_PORT.match(key):
                value = _retarget_port(value, moved)

            if key in entries:
                kept = entries[key]
                if strip_defaults(kept) == strip_defaults(value):
                    # Same references, different spelling. Prefer the one that still has
                    # something to fall back on.
                    if has_default(value) and not has_default(kept):
                        entries[key] = value
                    continue
                warnings.append(
                    f"label {key}: {owner[key]} wants {kept!r} but "
                    f"{service.spec.slug} wants {value!r}; kept the first — one "
                    f"container carries one value for a label. Settle it with "
                    f"labels.{key} in docker-bundle.yml"
                )
                continue
            entries[key] = value
            owner[key] = service.spec.slug

    entries.update(declared or {})
    return [f"{key}={_escape(value)}" for key, value in entries.items()], warnings


def _shm_size(plan: BundlePlan) -> tuple[str, list[str]]:
    """The bundle's ``shm_size``, taken from whichever baked service asked for one.

    Like a label it is container-wide, so several different requests cannot all be
    honoured; the first is kept and the rest reported.
    """
    chosen = ""
    owner = ""
    warnings: list[str] = []

    for service in plan.baked:
        declared = service.spec.shm_size
        if not declared:
            continue
        value = rename_variables(declared, plan.env_renames.get(service.spec.slug, {}))
        if not chosen:
            chosen, owner = value, service.spec.slug
        elif chosen != value:
            warnings.append(
                f"shm_size: {owner} wants {chosen!r} but {service.spec.slug} wants "
                f"{value!r}; kept the first — one container has one /dev/shm"
            )
    return chosen, warnings


def _retarget_port(value: str, moved: dict[int, int]) -> str:
    """Point a Traefik backend port at wherever the service actually ended up."""
    try:
        original = int(value)
    except ValueError:
        # A `${...}` reference; the deployment resolves it and we must not guess.
        return value
    return str(moved.get(original, original))


def _escape(value: str) -> str:
    """Make a label value safe inside the double-quoted YAML scalar the template emits."""
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _replica_vars(plan: BundlePlan) -> dict[str, int]:
    return {p.replicas_var: 1 for p in plan.programs if p.replicas_var}


#: A supervisord reference to an outer environment variable, ``%(ENV_NAME)s``.
_ENV_REF = re.compile(r"%\(ENV_([A-Za-z_][A-Za-z0-9_]*)\)s")


def _required_env(plan: BundlePlan) -> list[str]:
    """Names the image cannot start without.

    These are the keys a collision renamed: supervisord hands each program the name its
    application expects by referencing the renamed key, and the init phase exports the
    same mapping for the service's own entrypoint. Both fail hard when the name is not
    in the environment, and neither says where it was supposed to come from.

    Replica counts are excluded — the entrypoint gives those a default before supervisord
    starts, so an absent one is not a missing setting.
    """
    names: set[str] = set()
    for program in plan.programs:
        for value in program.environment.values():
            names.update(_ENV_REF.findall(value))
    for service in plan.baked:
        for value in service.init_env.values():
            names.update(referenced_names(value))
    return sorted(names - {p.replicas_var for p in plan.programs if p.replicas_var})


def _readiness_before_init(plan: BundlePlan) -> list:
    """Probes worth waiting on before init scripts run.

    Only data services qualify: application processes have not been released yet, so
    waiting for them would simply burn the timeout.
    """
    data_services = {
        service.spec.slug
        for service in plan.baked
        for program in service.programs
        if program.priority < INIT_BARRIER
    }
    return [probe for probe in plan.readiness if probe.label in data_services]


def _recipe_reason(service: PlannedService) -> str:
    return "kept outside the image by its recipe"


def stage_file(source: Path, destination: Path) -> None:
    """Copy one file into the build context, normalising text to LF.

    Everything staged here ends up inside a Linux image. A checkout on Windows hands us
    CRLF, and a shebang line ending in ``\\r`` makes the kernel report "no such file or
    directory" — which is why the source packages carry ``sed -i 's/\\r$//'`` in their own
    Dockerfiles. Normalising once here fixes it for every file, and keeps the context
    digest identical whatever the checkout did to line endings.

    Binary files are copied byte for byte: a NUL byte or invalid UTF-8 means the content
    is not text and must not be touched.
    """
    data = source.read_bytes()
    if b"\x00" not in data:
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            pass
        else:
            data = text.replace("\r\n", "\n").encode("utf-8")

    destination.write_bytes(data)
    shutil.copymode(source, destination)


def _stage_tree(source: Path, destination: Path) -> None:
    if source.is_dir():
        for entry in sorted(source.rglob("*")):
            if entry.is_dir():
                continue
            target = destination / entry.relative_to(source)
            target.parent.mkdir(parents=True, exist_ok=True)
            stage_file(entry, target)
    else:
        destination.parent.mkdir(parents=True, exist_ok=True)
        stage_file(source, destination)


def stage_context(plan: BundlePlan, context: Path, written: Written) -> None:
    """Copy everything the Dockerfile's COPY lines reference into ``context/``."""
    if context.exists():
        shutil.rmtree(context)
    context.mkdir(parents=True, exist_ok=True)

    for service in plan.baked:
        for copy in service.copies:
            if copy.from_stage:
                # Comes out of another image at build time; there is nothing on this
                # machine to stage.
                continue
            destination = context / copy.context
            destination.parent.mkdir(parents=True, exist_ok=True)
            _stage_tree(copy.source, destination)

    bundle_dir = context / "_bundle"
    bundle_dir.mkdir(parents=True, exist_ok=True)
    if plan.rootfs_stages:
        merge = resource_dir("render/assets") / "merge-rootfs.sh"
        _write(bundle_dir / "merge-rootfs.sh", merge.read_text(encoding="utf-8"), written,
               executable=True)


def render(
    plan: BundlePlan,
    output: Path,
    *,
    variant: str = "cpu",
    image_ref: str = "",
    labels: dict[str, str] | None = None,
) -> Written:
    """Write the whole ``dist/`` tree and return what was produced."""
    written = Written(directory=output, warnings=list(plan.warnings))
    env = _environment()
    output.mkdir(parents=True, exist_ok=True)

    context = output / "context"
    stage_context(plan, context, written)

    image_ref = image_ref or f"{plan.name}:latest"
    base_image = plan.base_images.get(variant, "debian:bookworm-slim")
    cuda = "cuda" in variant or "cuda" in base_image
    common = {
        "plan": plan,
        "header": HEADER.format(version=__version__),
        "header_plain": HEADER_PLAIN.format(version=__version__),
        "variant": variant,
        "base_image": base_image,
        "family": plan.family,
        "image_ref": image_ref,
        "cuda": cuda,
        "start_period": DEFAULT_START_PERIOD,
    }
    required_env = _required_env(plan)

    # supervisord
    _write(output / "supervisord.conf",
           env.get_template("supervisord.conf.j2").render(**common), written)
    _write(context / "_bundle" / "supervisord.conf",
           (output / "supervisord.conf").read_text(encoding="utf-8"), written)

    # entrypoint
    entrypoint = env.get_template("entrypoint.sh.j2").render(
        **common,
        needs_init=plan.needs_init,
        readiness_before_init=_readiness_before_init(plan),
        required_env=required_env,
    )
    _write(output / "entrypoint.sh", entrypoint, written, executable=True)
    _write(context / "_bundle" / "entrypoint.sh", entrypoint, written, executable=True)

    # healthcheck
    healthcheck = env.get_template("healthcheck.sh.j2").render(**common)
    _write(output / "healthcheck.sh", healthcheck, written, executable=True)
    _write(context / "_bundle" / "healthcheck.sh", healthcheck, written, executable=True)

    # Dockerfile last of the build inputs: its labels carry the digest of the finished
    # context, and that is only known once every file above has been staged.
    context_digest = _digest(context)
    _write(
        output / "Dockerfile",
        env.get_template("Dockerfile.j2").render(
            **common,
            install=plan.install.get(plan.family, []),
            run_steps=plan.run_steps.get(plan.family, []),
            exposed_ports=sorted({p.container for s in plan.baked for p in s.ports}),
            version=__version__,
            format_version=GENERATOR_VERSION,
            context_digest=context_digest,
            required_env=required_env,
        ),
        written,
    )

    # compose
    for service in plan.sidecars:
        service.recipe_reason = _recipe_reason(service)  # type: ignore[attr-defined]
    container_labels, label_warnings = _labels(plan, labels)
    written.warnings.extend(label_warnings)
    shm_size, shm_warnings = _shm_size(plan)
    written.warnings.extend(shm_warnings)
    _write(
        output / "docker-compose.yml",
        env.get_template("docker-compose.yml.j2").render(
            **common,
            published_ports=_published(plan),
            labels=container_labels,
            shm_size=shm_size,
            sidecar_labels={
                service.spec.name: [
                    f"{key}={_escape(value)}"
                    for key, value in service.spec.declared_labels.items()
                ]
                for service in plan.sidecars
            },
        ),
        written,
    )

    # .env.example
    _write(
        output / ".env.example",
        env.get_template("env.example.j2").render(
            **common,
            sections=_sections(plan.env),
            replica_vars=_replica_vars(plan),
        ),
        written,
    )

    _write(output / ".dockerignore", "context/**/.git\n**/__pycache__\n**/node_modules\n", written)
    _write(
        output / LOCK_NAME,
        _lock(plan, variant, image_ref, context_digest, required_env),
        written,
    )

    return written


def _lock(
    plan: BundlePlan,
    variant: str,
    image_ref: str,
    context_digest: str,
    required_env: list[str],
) -> str:
    """A record of what was generated: port map, digests, versions.

    Makes a regenerated ``dist/`` diffable and gives operators the port map in one place
    without reading the Dockerfile.
    """
    payload = {
        "generator": {"version": __version__, "format": GENERATOR_VERSION},
        "bundle": {"name": plan.name, "variant": variant, "image": image_ref},
        "base_image": plan.base_images.get(variant, ""),
        # What the flags were set to for this build. A generated dist/ otherwise says
        # nothing about which of the shapes described in the configuration it is.
        "features": dict(sorted(plan.features.items())),
        "ports": {
            slug: [
                {"original": p.original, "assigned": p.container, "moved": p.remapped}
                for p in entries
            ]
            for slug, entries in sorted(plan.port_map.items())
            if entries
        },
        "programs": [
            {
                "name": p.name,
                "priority": p.priority,
                "autostart": p.autostart,
                "scalable": p.scalable,
                "critical": p.critical,
            }
            for p in plan.programs
        ],
        "baked": sorted(s.spec.slug for s in plan.baked),
        "sidecars": sorted(s.spec.slug for s in plan.sidecars),
        "external": sorted(spec.slug for spec in plan.external),
        "volumes": dict(sorted(plan.named_volumes.items())),
        "env_renames": {k: dict(sorted(v.items())) for k, v in sorted(plan.env_renames.items())},
        # The environment contract of the image built from this dist/. The same list is
        # stamped on the image as a label, so a deployment can tell whether the .env it
        # holds was generated for the image it is about to run.
        "required_env": list(required_env),
        "context_digest": context_digest,
    }
    return yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, default_flow_style=False)


def _digest(context: Path) -> str:
    """A stable digest of the staged build context."""
    if not context.is_dir():
        return ""
    hasher = hashlib.sha256()
    for path in sorted(p for p in context.rglob("*") if p.is_file()):
        hasher.update(str(path.relative_to(context)).replace("\\", "/").encode())
        hasher.update(path.read_bytes())
    return f"sha256:{hasher.hexdigest()}"
